server:
  address: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://windev.mysql.database.azure.com:3306/lbms
    username: reda
    password: redame0010@
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 # 2h
    refreshTokenExpiration: 604800 # 7d
  mail:
    host: smtp.gmail.com
    port: 587
    username: redaajdi6@gmail.com
    password: lkwe pbef fsds edbh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
logging:
  level:
    org:
      springframework:
        security=DEBUG: