spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://windev.mysql.database.azure.com:3306/lbms
    username: reda
    password: redame0010@
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 # 2h
    refreshTokenExpiration: 604800 # 7d